# AWS configuration for storing images and assets with Paperclip
bucket:             <%= ENV['S3_BUCKET'] %>
access_key_id:      <%= ENV['S3_ACCESS_KEY_ID'] %>
secret_access_key:  <%= ENV['S3_SECRET_ACCESS_KEY'] %>

